### ISSUE TITLE
3.1.0.0: InvalidCastException with some plugins.

### ISSUE THREAD

**Issue by Squirrelies** [Squirrelies/SRTHost#26]
The following exception occurs when loading the SRT:
```
[InvalidCastException] System.InvalidCastException: Unable to cast object of type 'SRTPluginProviderRE8.GameMemoryRE8' to type 'SRTPluginProviderRE8.IGameMemoryRE8'.
   at SRTPluginUIRE2DirectXOverlay.SRTPluginUIRE2DirectXOverlay.ReceiveData(Object gameMemory) in C:\Users\video\source\repos\ResidentEvilSpeedrunning\SRTPluginUIRE8DirectXOverlay\SRTPluginUIRE8DirectXOverlay\SRTPluginUIRE8DirectXOverlay.cs:line 163
   at SRTHost.Program.PluginReceiveData[T](IPluginStateValue`1 plugin, Object gameMemory)
```

All plugins and host are the latest versions. At the time of this post, SRT Host's latest version is 3.1.0.0.

**Comment by Squirrelies** [comment]
SRT Host 3.1.0.0 is crashing because it is finding SRTPluginProviderRE8.dll in both SRTPluginUIRE8DirectXOverlay/SRTPluginProviderRE8.dll (which is bad) and SRTPluginProviderRE8/SRTPluginProviderRE8.dll (which is correct).

SRT Host will prefer finding dependencies in its own folder first, then it will check other plugin folders after. Since it finds the provider in its folder, it uses that. When it receives data from the actual loaded provider, since the interface came from an assembly different than the one the ui plugin has loaded, an invalid cast exception is thrown.

This is caused by a lack of "Private" and "ExcludeAssets" tags in the csproj for the DirectXOverlay project.

See RE2 REmake's DirectX Overlay vs RE8's DirectX Overlay:

https://github.com/SpeedrunTooling/SRTPluginUIRE2DirectXOverlay/blob/f0eca0bdfafab40a72ea7413701e143f33b0cd74/SRTPluginUIRE2DirectXOverlay/SRTPluginUIRE2DirectXOverlay.csproj#L46
https://github.com/SpeedrunTooling/SRTPluginUIRE8DirectXOverlay/blob/0a06bff751c65abfcfeae402cc50d5be81724db5/SRTPluginUIRE8DirectXOverlay/SRTPluginUIRE8DirectXOverlay.csproj#L50

I will see if I can add a non-hackish way to handle this in SRT Host but the RE8 DXOverlay plugin needs work to fix the RE2 references in it and to fix that tag.
